language: python
os:
  - linux
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source unicorn_binance_websocket_api unittest_binance_websocket_api.py
after_success:
  - coveralls
after_script:
  - bash ./tools/travis_telegram_notification.sh
