name: unicorn-binance-websocket-api
dependencies:
- python>=3.6.1
- pip:
  - cheroot
  - colorama
  - flask
  - flask_restful
  - pathlib
  - requests
  - ujson
  - websocket-client
  - websockets==8.1