name: unicorn-binance-websocket-api
dependencies:
- python>=3.5.3
- pip:
  - cheroot
  - colorama
  - flask
  - flask_restful
  - pathlib
  - requests
  - simplejson
  - websocket-client
  - websockets==7.0